[build]
  [build.environment]
    REACT_APP_SENTRY_DSN = "https://e5ddde2bbf98433eb0dfc0ed47241d28@o296332.ingest.sentry.io/4113637"
    REACT_APP_HOTJAR_HJID = "1888019"
    REACT_APP_HOTJAR_HJSV = "6"
    REACT_APP_OAUTH2_GOOGLE_CLIENT_ID = "enabled"
    REACT_APP_OAUTH2_GITHUB_CLIENT_ID = "enabled"
    REACT_APP_SEGMENT_KEY = "9OnZ6LnDztuZZo4zXfoutEEBB2wftHUH"
#    REACT_APP_MARKETPLACE_URL = "https://release-marketplace.appsmith.com"
    REACT_APP_OPTIMIZELY_KEY = "Jq3K2kVdvuvxecHyHbVYcj"
    REACT_APP_ALGOLIA_API_ID = "AZ2Z9CJSJ0"
    REACT_APP_ALGOLIA_API_KEY = "d113611dccb80ac14aaa72a6e3ac6d10"
    REACT_APP_ALGOLIA_SEARCH_INDEX_NAME = "test_appsmith"
    REACT_APP_CLIENT_LOG_LEVEL = "debug"
    REACT_APP_GOOGLE_MAPS_API_KEY = "AIzaSyBOQFulljufGt3VDhBAwNjZN09KEFufVyg"
    REACT_APP_TNC_PP = "true"

[context.production]
  [context.production.environment]
    REACT_APP_ENVIRONMENT = "PRODUCTION"
    REACT_APP_BASE_URL = "https://api.appsmith.com"
    APP_HOST = "app.appsmith.com"
    REACT_APP_SENTRY_DSN = "https://78e9c79f210f4f83ab6d96e097f47b6f@o296332.ingest.sentry.io/1546547"
    REACT_APP_CLIENT_LOG_LEVEL = "error"

[context.release]
  [context.release.environment]
    REACT_APP_ENVIRONMENT = "STAGING"
    REACT_APP_BASE_URL = "https://release-api.appsmith.com"
    APP_HOST = "release.app.appsmith.com"

[context.deploy-preview]
  [context.deploy-preview.environment]
    REACT_APP_ENVIRONMENT = "STAGING"
    REACT_APP_BASE_URL = "https://release-api.appsmith.com"
    # Not adding an APP_HOST here because the URL is dynamic in nature and cannot be determined.


[[headers]]
  for = "/static/*"
  [header.values]
    cache-control = "max-age=604800"

[[redirects]]
  from = "/api/*"
  to = "API_PLACEHOLDER/api/:splat"
  status = 200
  force = true
  headers = { X-Forwarded-Host = "APP_HOST_PLACEHOLDER", X-Forwarded-Proto = "https" }

[[redirects]]
  from = "/oauth2/*"
  to = "API_PLACEHOLDER/oauth2/:splat"
  status = 200
  force = true
  headers = { X-Forwarded-Host = "APP_HOST_PLACEHOLDER", X-Forwarded-Proto = "https" }

[[redirects]]
  from = "/login/*"
  to = "API_PLACEHOLDER/login/:splat"
  status = 200
  force = true
  headers = { X-Forwarded-Host = "APP_HOST_PLACEHOLDER", X-Forwarded-Proto = "https" }

[[redirects]]
  from = "/f/*"
  to = "https://cdn.optimizely.com/:splat"
  status = 200
  force = true

# This must be the last redirect in the chain because it's a catch-all
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200