[context.production]
  [context.production.environment]
    REACT_APP_ENVIRONMENT = "PRODUCTION"

[context.release]
  [context.release.environment]
    REACT_APP_ENVIRONMENT = "STAGING"

[context.develop]
  [context.develop.environment]
    REACT_APP_ENVIRONMENT = "DEVELOPMENT"

[context.a]
  [context.a.environment]
    REACT_APP_ENVIRONMENT = "STAGING"

[context.b]
  [context.b.environment]
    REACT_APP_ENVIRONMENT = "STAGING"
