[[headers]]
  for = "/static/*"
  [header.values]
    cache-control = "max-age=604800"

[context.production]
  [context.production.environment]
    REACT_APP_ENVIRONMENT = "PRODUCTION"
    REACT_APP_BASE_URL = "https://api.appsmith.com"
    APP_URL = "https://app.appsmith.com"

[context.release]
  [context.release.environment]
    REACT_APP_ENVIRONMENT = "STAGING"
    REACT_APP_BASE_URL = "https://release-api.appsmith.com"
    APP_URL = "https://release.app.appsmith.com"

[context.develop]
  [context.develop.environment]
    REACT_APP_ENVIRONMENT = "DEVELOPMENT"
    REACT_APP_BASE_URL = "https://release-api.appsmith.com"
    APP_URL = "https://develop.app.appsmith.com"

[context.a]
  [context.a.environment]
    REACT_APP_ENVIRONMENT = "STAGING"
    REACT_APP_BASE_URL = "https://release-api.appsmith.com"
    APP_URL = "https://a.app.appsmith.com"

[context.b]
  [context.b.environment]
    REACT_APP_ENVIRONMENT = "STAGING"
    REACT_APP_BASE_URL = "https://release-api.appsmith.com"
    APP_URL = "https://b.app.appsmith.com"

[context.deploy-preview]
  [context.deploy-preview.environment]
    REACT_APP_ENVIRONMENT = "STAGING"
    REACT_APP_BASE_URL = "https://release-api.appsmith.com"
    # Not adding an APP_URL here because the URL is dynamic in nature and cannot be determined.

[[redirects]]
  from = "/api/*"
  to = "API_PLACEHOLDER/api/:splat"
  status = 200
  force = true
  headers = { Host = "APP_URL_PLACEHOLDER" }

[[redirects]]
  from = "/oauth2/*"
  to = "API_PLACEHOLDER/oauth2/:splat"
  status = 200
  force = true
  headers = { Host = "APP_URL_PLACEHOLDER" }

# This must be the last redirect in the chain because it's a catch-all
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200